name: Clean Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov passlib[argon2] cryptography

      - name: Setup test environment
        run: |
          mkdir -p tests/tmp
          python -c "import passlib.hash; print('Argon2 version:', passlib.hash.argon2.__version__)"
          
      - name: Run tests
        run: |
          PYTHONPATH=. pytest -v tests/test_hashing.py --cov=security --cov-report=term-missing 