name: Clean Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          # Setup directories
          mkdir -p tests/tmp
          # Run a basic test
          pytest -xvs tests/test_hashing.py 