name: Test PR with Fixes

on:
  pull_request:
    paths:
      - 'tests/**'
      - 'memory/**'
      - 'security/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/**'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  test-fixes:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install core dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      
      - name: Install encryption dependencies
        run: |
          pip install cryptography>=41.0.0 passlib>=1.7.4 argon2-cffi>=21.3.0
      
      - name: Create test directories
        run: |
          mkdir -p tests/tmp
      
      - name: Set environment variables
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
          echo "HF_HUB_DISABLE_SYMLINKS_WARNING=1" >> $GITHUB_ENV
      
      - name: Test hashing module
        run: |
          python -m pytest tests/test_hashing.py -v
      
      - name: Test secure memory module
        run: |
          python -m pytest tests/test_secure_memory.py -v
      
      - name: Install embedding dependencies
        run: |
          pip install numpy>=1.21.0
          pip install --no-deps sentence-transformers==2.2.2
          pip install torch --index-url https://download.pytorch.org/whl/cpu
      
      - name: Test embedding memory module
        continue-on-error: true
        run: |
          python -m pytest tests/test_embedding_memory.py -v 